[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cgol"
dynamic = ["version"]
description = "A simple Conway's Game of Life simulator in Python."
readme = "README.md"
requires-python = ">=3.14"
license = { file = "LICENSE" }
authors = [
    { name = "Morpheus" }
]
classifiers = [
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.14",
    "Topic :: Education",
    "Topic :: Games/Entertainment :: Simulation",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Life",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]

dependencies = [
    "pygame-ce>=2.5.0",
]

[project.urls]
"Source" = "https://github.com/TheGittyPerson/conways-game-of-life"
"Bug Reports" = "https://github.com/TheGittyPerson/conways-game-of-life/issues"

[project.scripts]
conway-life = "cgol.__main__:main"

[tool.setuptools]
packages = ["cgol"]

[tool.setuptools.package-data]
cgol = ["assets/*", "assets/**/*"]

[tool.setuptools.dynamic]
version = { attr = "cgol.__version__" }
